### PR TITLE
Game state loading and config updates

### PR DESCRIPTION
**Pull request by jtegtmeier**
Changed:

- the way that assets are initialized in the loadGame function (was resetState) is shortened
- doors know how to connect and add references to their adjacent rooms in construction
- config changed to only specify which rooms and how they are connected in the doors section of the file
- added const specifiers to class properties that are not redefined at run-time
- removed unused constructor parameters in the room class (and maybe a couple in other classes)

### CODE REVIEW

**Comment by jtegtmeier** [comment]
Let's make sure to rebase this branch if/when merging. Most of the individual commits I made are unnecessary for master's history.

**Comment by jdsandifer** [comment]
Cool, here are my thoughts...

**Things I love:**
- Moving the directional information for the doors to the door items in config.js is awesome! I love that it relieves the rooms of that info and removes the circular references. It was annoying to edit that stuff - that makes it a lot easier. Doors can be removed or added without affecting the room data now, too. Good stuff!
- I like the new loadGame function and its calling command (ES6 syntax) - it's definitely more readable.
- Good call on removing the unneeded constructor parameters.
- Thanks for adding more const specifiers. I've been fixing those as I go so thanks for taking care of more of them.
- Moving the room display stuff to one function is great.

**One thing I'm ambivalent about:**
- Adding the code in Door to have them "construct" themselves is pretty neat. However, by shifting that task from the loadGame() function to the Door, it increasing coupling between Door and Room. It's still loose in that it relies on Room's addDoor function, but it's something to think about.

**Problems or things I don't like, but also don't mind if we fix later:**
- debugDisplayRoomData() - Still don't understand why you're calling this debug. Displaying room data - even if it's eventually not going to show items - is an essential game function, right? Even if it's going to be moved later, I don't like calling it debug unless it can be removed without affecting the game. (You could comment the item display line as debug, but the other stuff is essential to the game.)
- The "pathway" door should be located on the east side of the Backyard for the little example world we're using right now. (Yes, same side on both rooms.)

**Things that I'd like to see changed before merging:**
- I think that changing the items and entities section of config.js to use keys ("cheese":{}, "knife":{}) reduces the coherence of its structure. Especially, in the case of items - they no longer have a name as far as the casual observer can tell.
I know it's more efficient and makes it easier for you to avoid itemByName()-like functions, but I'm not a fan because it makes writing the config more like programming and less clear as to what's what (not as self-documenting).
Some suggestions for possible solutions:
    a. Move entities and items into the rooms like you mentioned during our discussion the other day, keeping the old structure - items: [{name:"cheese", etc.},{name:"knife",etc.}] (I like this solution best.)
    b. Remove the keys, make sure each asset has a name: "" property and just search through them as before.

- You rely on find() in two places in loadGame() which will return undefined if no object is found (e.g. if there's a typo in config.js). Wouldn't be a big deal except it replaced my functions that had basic error checking. (If you refactor code, make sure you don't reduce functionality.)

**Comment by jtegtmeier** [comment]
Thanks for the quick feedback.

Responses to concerns:

- I thought for a while on the coupling and circular references our doors/rooms have. At first I tried to see what an implementation would look like that eliminated the references each other, and instead just used id's for door/rooms. This would allow us to construct all game objects all at once without needing to set up references later and would slightly reduce coupling. in the end, I decided that coupling our objects wasn't a big deal for this project and when with the solution that I think will allow the least amount of code for our small (so far) project.
- debugDisplayRoomData() is not worked out and can be removed if you would like. I think that functionality should be moved into the messenger class or removed depending on what we want our ui to look like. Need to talk with Brian on this.
- I agree with the error handling on construction (and eventually in other parts of the app), especially as our objects become bigger and more nested. We talked about adding a function or class that could handle dirty input and I think this would be a good way to approach this. For now, I can add a function to the game class that either returns the ref/value if the operation was not falsy, or logs an error detailing the operation that fails. We could also think about type checking as the app becomes more mature. https://flow.org/ is really popular in JS right now.

Disagreement:

- I am not sure I agree that the creating unique keys for entities and items reduces the coherence of the config file. The idea in my mind is that objects(rooms/doors) that go in an array structure will be looped through once on construction and will contain item/entity keys that map to setup data for objects that may be used more then once in our game. For example having two different candy bars with the same effects to the player in the study and the kitchen. To me, JSON provides an easy way to map objects using a key and looks like a clear enough way to "name" the unique object. We could add a name property to the item objects if that helps my case. Let me know what you think on this, maybe you see items/entities as only ever being used once in our game.

**Comment by jdsandifer** [comment]
**Regarding debugDisplayRoomData():** Just remove the debug prefix and I'd be happy with it as is. I agree we should eventually move it, too, but don't care about that right now. One thing at a time.

**Error handling:** Sounds, good. Just make sure you list the bad value that was being searched for. I'm not looking for anything better than was already there right now, just asking for it to not do less than it did before you changed it.

**Config.js**: The item/entity template idea is reasonable and might be helpful in the future, but I think we need to remember KISS and YAGNI and stick to what's needed right now. Even if we later add multiple objects of the same type, it may be easier and more readable to copy and paste a couple objects than to create a templating structure.
I also don't remember talking about changing the config file structure at all for this iteration, but if you want to change it, I would rather go with your other idea of putting the items inside the room/player/entity definitions themselves because it's logical, readable, and removes another cross-reference. It should be easy to work with that structure and still avoid the itemByName function that you're trying to remove.

**Comment by jtegtmeier** [comment]
- renamed the debugDisplayRoomData function
- added basic falsy error handling
- in my mind changing the item/entity arrays to key/value object was the simple solution instead of searching through the items array each time a item is needed in a room (like the way it was). Let me know if you disagree. 

Thanks,

**Comment by jdsandifer** [comment]
The error handling looks great! I would just change the name a little - maybe objectOrError() since it returns an object if things are ok. (I think "success" falls into the same category of words as "right", "correct", etc. that should be avoided in names because it's not clear what they mean.)

I agree that your change to config.js is simpler _in the setState() function_. I just disagree that that should be a priority. I think _keeping config.js as simple as possible_ is more important. As this develops into a full-blown text game engine, hopefully other people will want to use it to create games. All they have to do is change out the config to create a new game so keeping the config structure simple makes that easier; it's essentially the UI for game developers. (Eventually, I'd like to see it become a text file that we parse so it's even simpler - like I've seen in most game configs I've looked at. But let's at least not make it more complex right now.)

**Comment by jtegtmeier** [comment]
- the successOrError does not always return an object. It depends on what is passed to it. Could be a num, array or obj.

I do not want misinterpreting our vision for the future of the config file to hold us back. We will not always see eye to eye on what looks simple. Please make the changes to the config structure and item creation the way you see it and lets merge. Thanks!

**Comment by jdsandifer** [comment]
**Regarding `successOrError()`:** If you want it to be a general error function, that's fine. I would just suggest picking a word that covers the possible return values in a more specific way - maybe `validItemOrError()` or even `truthyItemOrError()`.

But that's just feedback - I assume we'll be changing it again later so I'm not worried about it right now.

**Regarding config.js:** This pull request is mainly about you changing working code I wrote into more the way you want it to look so please don't ask me to undo your changes (i.e. re-write my own code). Refactoring is important and you've made some good improvements which I fully support, but you have to take responsibility for correcting/undoing what's not unanimously considered an improvement.

If you're just confused about specifics: Just copy and paste the items section of config.js from master and change the new setState() to work with it.

Also, there's a way to avoid looping through the items each time you need to locate one by name in setState() without changing the config to what you have currently. If that's the main thing you're trying to avoid, thinking of it like an algorithm challenge might help you figure out the other solution.

**Hang in there, dude!** True teamwork is hard because _there are always differences of opinion_, but if you stick with it, listen to your teammates, and compromise here and there you will reap the rewards. It's hard, but it's totally worth it.

**Pull request merged**
